bucket         = "tf-state-7afc2a05"
key            = "dev/terraform.tfstate" # Unique path for this project
region         = "us-east-1"
dynamodb_table = "terraform-locks" # For state locking
encrypt        = true

